name: 'Update README'

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * * '

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update the README file      
    steps: 
    - name: Run Python script
      uses: actions/checkout@v4
    - run: |
          output=$(python code.py)
          
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Updated README.md