name: 'Update README'

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * * '

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update the README file      
    steps: 
    - name: Run Python script
      uses: actions/checkout@v2
    - run: |
          output=$(python code.py)