name: 'Update README'

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * * '

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update the README file      
    steps: 
    - name: Run Python script
      uses: actions/checkout@v2
    - run: |
          python code.py
      id: step1
    - name: Commit changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Update progress bar"
        git push